#!/usr/bin/env node
//
// Downloads article photos listed in content/images/sources.json from Wikimedia
// Commons, then rewrites the generated half of CREDITS.md.
//
// Why fetch rather than commit binaries: the licence and the author line are
// facts that live on Commons, not in this repo. Reading them at fetch time means
// the credit printed under a photo is whatever Commons currently says, and a
// file whose licence has been changed or revoked fails loudly here instead of
// sitting on a commercial site under a stale credit.
//
// Run with: npm run fetch:images

import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const DIR = path.join(ROOT, "content", "images");
const MANIFEST = path.join(DIR, "sources.json");
const CREDITS = path.join(DIR, "CREDITS.md");
const API = "https://commons.wikimedia.org/w/api.php";
const UA = "JagOBXproperties-image-fetcher/1.0 (https://jagobxproperties.com)";

// Licences that allow commercial use. Anything else (NonCommercial, NoDerivs,
// "fair use", unknown) is refused: this is a business site, not a wiki.
const ALLOWED = /^(public domain|cc0|cc by(?:[- ]sa)?[- ]?\d?(\.\d)?)/i;

const strip = (s) => String(s || "").replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim();

async function commonsInfo(titles, width) {
  const url = new URL(API);
  url.searchParams.set("action", "query");
  url.searchParams.set("titles", titles.map((t) => `File:${t}`).join("|"));
  url.searchParams.set("prop", "imageinfo");
  url.searchParams.set("iiprop", "url|size|extmetadata");
  url.searchParams.set("iiurlwidth", String(width));
  url.searchParams.set("format", "json");
  url.searchParams.set("formatversion", "2");

  const res = await fetch(url, { headers: { "User-Agent": UA, accept: "application/json" } });
  if (!res.ok) throw new Error(`Commons API ${res.status} ${res.statusText}`);
  const data = await res.json();

  const out = new Map();
  for (const page of data.query?.pages || []) {
    if (page.missing) {
      out.set(page.title.replace(/^File:/, ""), { missing: true });
      continue;
    }
    const ii = page.imageinfo?.[0] || {};
    const e = ii.extmetadata || {};
    out.set(page.title.replace(/^File:/, ""), {
      url: ii.thumburl || ii.url,
      licence: strip(e.LicenseShortName?.value) || "unknown",
      artist: strip(e.Artist?.value) || "",
      descUrl: ii.descriptionurl || "",
    });
  }
  return out;
}

async function download(url, dest) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  const buf = Buffer.from(await res.arrayBuffer());
  if (buf.length < 5000) throw new Error(`suspiciously small download (${buf.length} bytes)`);
  fs.writeFileSync(dest, buf);
  return buf.length;
}

function rewriteCredits(rows) {
  const marker = "<!-- fetched:start -->";
  const endMarker = "<!-- fetched:end -->";
  const table = [
    marker,
    "",
    "## Fetched photos",
    "",
    "Generated by `npm run fetch:images` from `sources.json`. Do not edit by hand:",
    "the licence and credit columns are read from the Wikimedia Commons API each run.",
    "",
    "| File | Subject | Source | Licence | Credit needed |",
    "| --- | --- | --- | --- | --- |",
    ...rows.map(
      (r) =>
        `| ${r.file} | ${r.subject} | Wikimedia Commons, ${r.commons} | ${r.licence} | ${
          r.artist || "none"
        } |`
    ),
    "",
    endMarker,
  ].join("\n");

  let existing = fs.existsSync(CREDITS) ? fs.readFileSync(CREDITS, "utf8") : "";
  const start = existing.indexOf(marker);
  const end = existing.indexOf(endMarker);
  if (start !== -1 && end !== -1) {
    existing = existing.slice(0, start) + table + existing.slice(end + endMarker.length);
  } else {
    existing = `${existing.trimEnd()}\n\n${table}\n`;
  }
  fs.writeFileSync(CREDITS, existing, "utf8");
}

async function main() {
  if (!fs.existsSync(MANIFEST)) {
    console.log("No content/images/sources.json, nothing to fetch.");
    return;
  }
  const manifest = JSON.parse(fs.readFileSync(MANIFEST, "utf8"));
  const images = manifest.images || [];
  const width = manifest.width || 1400;
  if (!images.length) {
    console.log("Manifest lists no images.");
    return;
  }

  const info = await commonsInfo(images.map((i) => i.commons), width);

  const rows = [];
  const problems = [];
  let fetched = 0;

  for (const item of images) {
    const meta = info.get(item.commons);
    if (!meta || meta.missing) {
      problems.push(`${item.file}: not found on Commons as "${item.commons}"`);
      continue;
    }
    if (!ALLOWED.test(meta.licence)) {
      problems.push(
        `${item.file}: licence "${meta.licence}" does not clearly allow commercial use`
      );
      continue;
    }

    rows.push({ ...item, licence: meta.licence, artist: meta.artist });

    const dest = path.join(DIR, item.file);
    if (fs.existsSync(dest)) {
      console.log(`have  ${item.file}`);
      continue;
    }
    const bytes = await download(meta.url, dest);
    fetched += 1;
    console.log(`saved ${item.file} (${Math.round(bytes / 1024)} KB, ${meta.licence})`);
  }

  if (problems.length) {
    console.error("\nRefusing to continue:");
    for (const p of problems) console.error(`  ${p}`);
    process.exit(1);
  }

  rewriteCredits(rows);
  console.log(`\n${fetched} new file(s). ${rows.length} entries written to CREDITS.md.`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
